osx_image: xcode8.1
language: objective-c

script:
 - xcodebuild test -workspace TKCurrencyTextField.xcworkspace -scheme Example -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.1' ONLY_ACTIVE_ARCH=NO | xcpretty